// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain;

import com.bfds.saec.domain.Tranch;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Tranch_Roo_Configurable {
    
    declare @type: Tranch: @Configurable;
    
}
