CREATE TABLE WC1U999S ( KEY_DATE    DATE, KEY_TIME    TIME, KEY_MILSEC   VARCHAR(6), RECORDCD    VARCHAR(1), CRNODE    VARCHAR(2), EVENT_DATTIM   TIMESTAMP, ENDDATTIM    TIMESTAMP );

CREATE TABLE WA5U999S ( KEY_DATE   DATE, KEY_TIME   TIME, KEY_MILSEC  VARCHAR(6), RECORDCD   VARCHAR(1), CRNODE   VARCHAR(2), EVENT_DATTIM   TIMESTAMP, WRKTYPE   VARCHAR(10), UNITCD   VARCHAR(10), STATCD   VARCHAR(10) );

CREATE TABLE PS027PF ( KEY_DATE   DATE, KEY_TIME   TIME, KEY_MILSEC  VARCHAR(6), RECORDCD   VARCHAR(1), CRNODE   VARCHAR(2), SSNO  VARCHAR(9), AMTV  VARCHAR(15), CKNM  VARCHAR(9), MLID  VARCHAR(6) );