CREATE TABLE SAEC.WC1U999S ( KEY_DATE    DATE, KEY_TIME    TIME, KEY_MILSEC   CHAR(6), RECORDCD    CHAR(1), CRNODE    CHAR(2), EVENT_DATTIM   TIMESTAMP, ENDDATTIM    TIMESTAMP );

CREATE TABLE SAEC.WA5U999S ( KEY_DATE   DATE, KEY_TIME   TIME, KEY_MILSEC  CHAR(6), RECORDCD   CHAR(1), CRNODE   CHAR(2), EVENT_DATTIM   TIMESTAMP, WRKTYPE   CHAR(10), UNITCD   CHAR(10), STATCD   CHAR(10) );

CREATE TABLE SAEC.PS027PF ( KEY_DATE   DATE, KEY_TIME   TIME, KEY_MILSEC  CHAR(6), RECORDCD   CHAR(1), CRNODE   CHAR(2), SSNO  CHAR(9), AMTV  CHAR(15), CKNM  CHAR(9), MLID  CHAR(6) );