// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.encorr;

import com.bfds.saec.encorr.EncorrItemDataOnDemand;
import com.bfds.saec.encorr.EncorrItemIntegrationTest;
import com.bfds.saec.encorr.dao.EncorrItem;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EncorrItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EncorrItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EncorrItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EncorrItemIntegrationTest: @Transactional;
    
    @Autowired
    private EncorrItemDataOnDemand EncorrItemIntegrationTest.dod;
    
    @Test
    public void EncorrItemIntegrationTest.testCountEncorrItems() {
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to initialize correctly", dod.getRandomEncorrItem());
        long count = EncorrItem.countEncorrItems();
        Assert.assertTrue("Counter for 'EncorrItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EncorrItemIntegrationTest.testFindEncorrItem() {
        EncorrItem obj = dod.getRandomEncorrItem();
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to provide an identifier", id);
        obj = EncorrItem.findEncorrItem(id);
        Assert.assertNotNull("Find method for 'EncorrItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EncorrItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EncorrItemIntegrationTest.testFindAllEncorrItems() {
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to initialize correctly", dod.getRandomEncorrItem());
        long count = EncorrItem.countEncorrItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'EncorrItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EncorrItem> result = EncorrItem.findAllEncorrItems();
        Assert.assertNotNull("Find all method for 'EncorrItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EncorrItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EncorrItemIntegrationTest.testFindEncorrItemEntries() {
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to initialize correctly", dod.getRandomEncorrItem());
        long count = EncorrItem.countEncorrItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EncorrItem> result = EncorrItem.findEncorrItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EncorrItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EncorrItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EncorrItemIntegrationTest.testFlush() {
        EncorrItem obj = dod.getRandomEncorrItem();
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to provide an identifier", id);
        obj = EncorrItem.findEncorrItem(id);
        Assert.assertNotNull("Find method for 'EncorrItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEncorrItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EncorrItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EncorrItemIntegrationTest.testMergeUpdate() {
        EncorrItem obj = dod.getRandomEncorrItem();
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to provide an identifier", id);
        obj = EncorrItem.findEncorrItem(id);
        boolean modified =  dod.modifyEncorrItem(obj);
        Integer currentVersion = obj.getVersion();
        EncorrItem merged = (EncorrItem)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EncorrItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EncorrItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to initialize correctly", dod.getRandomEncorrItem());
        EncorrItem obj = dod.getNewTransientEncorrItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EncorrItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'EncorrItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EncorrItemIntegrationTest.testRemove() {
        EncorrItem obj = dod.getRandomEncorrItem();
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EncorrItem' failed to provide an identifier", id);
        obj = EncorrItem.findEncorrItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EncorrItem' with identifier '" + id + "'", EncorrItem.findEncorrItem(id));
    }
    
}
