/*
 * (c) Copyright 2005-2011 JAXIO - Generated by Celerio, a Jaxio tool. http://www.jaxio.com
 */
package com.bfds.saec.security.utils;

import com.bfds.saec.domain.util.AccountContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.webflow.execution.FlowExecutionListenerAdapter;
import org.springframework.webflow.execution.RequestContext;

import javax.servlet.http.HttpServletRequest;

@Component
public class AccountContextListener extends FlowExecutionListenerAdapter {

    @Autowired
    private AccountContextSupport accountContextSupport;

    public void requestSubmitted(RequestContext context) {
        accountContextSupport.processAccountContext((HttpServletRequest) context.getExternalContext()
                .getNativeRequest());
        ((HttpServletRequest) context.getExternalContext().getNativeRequest()).setAttribute("accountContext",
                AccountContext.getAccountContext());
    }

    public void requestProcessed(RequestContext context) {
        accountContextSupport.resetContext();
    }
}