// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.wss.domain.reference;

import com.bfds.wss.domain.reference.ProofType;

privileged aspect ProofType_Roo_JavaBean {
    
    public String ProofType.getCode() {
        return this.code;
    }
    
    public void ProofType.setCode(String code) {
        this.code = code;
    }
    
}
