// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.rip.domain;

import com.bfds.saec.rip.domain.CureLetterRipObjectIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CureLetterRipObjectIntegrationTest_Roo_Configurable {
    
    declare @type: CureLetterRipObjectIntegrationTest: @Configurable;
    
}
