// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.rip.domain;

import com.bfds.saec.rip.domain.CureLetterRipObject;
import com.bfds.saec.rip.domain.CureLetterRipObjectDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CureLetterRipObjectDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CureLetterRipObjectDataOnDemand: @Component;
    
    private Random CureLetterRipObjectDataOnDemand.rnd = new SecureRandom();
    
    private List<CureLetterRipObject> CureLetterRipObjectDataOnDemand.data;
    
    public CureLetterRipObject CureLetterRipObjectDataOnDemand.getNewTransientCureLetterRipObject(int index) {
        CureLetterRipObject obj = new CureLetterRipObject();
        setAddress1(obj, index);
        setAddress2(obj, index);
        setAddress3(obj, index);
        setAddress4(obj, index);
        setAddress5(obj, index);
        setAddress6(obj, index);
        setBusinessUnit(obj, index);
        setCity(obj, index);
        setCorrelationId(obj, index);
        setCreatedByUser(obj, index);
        setHostName(obj, index);
        setLetterCode(obj, index);
        setReferenceNo(obj, index);
        setRegistration1(obj, index);
        setRegistration2(obj, index);
        setRegistration3(obj, index);
        setRegistration4(obj, index);
        setRegistration5(obj, index);
        setRegistration6(obj, index);
        setSpecialInstructions(obj, index);
        setStateCode(obj, index);
        setStatus(obj, index);
        setWorkType(obj, index);
        setZipCode(obj, index);
        setZipExt(obj, index);
        return obj;
    }
    
    public void CureLetterRipObjectDataOnDemand.setAddress1(CureLetterRipObject obj, int index) {
        String address1 = "address1_" + index;
        obj.setAddress1(address1);
    }
    
    public void CureLetterRipObjectDataOnDemand.setAddress2(CureLetterRipObject obj, int index) {
        String address2 = "address2_" + index;
        obj.setAddress2(address2);
    }
    
    public void CureLetterRipObjectDataOnDemand.setAddress3(CureLetterRipObject obj, int index) {
        String address3 = "address3_" + index;
        obj.setAddress3(address3);
    }
    
    public void CureLetterRipObjectDataOnDemand.setAddress4(CureLetterRipObject obj, int index) {
        String address4 = "address4_" + index;
        obj.setAddress4(address4);
    }
    
    public void CureLetterRipObjectDataOnDemand.setAddress5(CureLetterRipObject obj, int index) {
        String address5 = "address5_" + index;
        obj.setAddress5(address5);
    }
    
    public void CureLetterRipObjectDataOnDemand.setAddress6(CureLetterRipObject obj, int index) {
        String address6 = "address6_" + index;
        obj.setAddress6(address6);
    }
    
    public void CureLetterRipObjectDataOnDemand.setBusinessUnit(CureLetterRipObject obj, int index) {
        String businessUnit = "businessUnit_" + index;
        obj.setBusinessUnit(businessUnit);
    }
    
    public void CureLetterRipObjectDataOnDemand.setCity(CureLetterRipObject obj, int index) {
        String city = "city_" + index;
        obj.setCity(city);
    }
    
    public void CureLetterRipObjectDataOnDemand.setCorrelationId(CureLetterRipObject obj, int index) {
        Long correlationId = new Integer(index).longValue();
        obj.setCorrelationId(correlationId);
    }
    
    public void CureLetterRipObjectDataOnDemand.setCreatedByUser(CureLetterRipObject obj, int index) {
        String createdByUser = "createdByUser_" + index;
        obj.setCreatedByUser(createdByUser);
    }
    
    public void CureLetterRipObjectDataOnDemand.setHostName(CureLetterRipObject obj, int index) {
        String hostName = "hostName_" + index;
        obj.setHostName(hostName);
    }
    
    public void CureLetterRipObjectDataOnDemand.setLetterCode(CureLetterRipObject obj, int index) {
        String letterCode = "letterCode_" + index;
        obj.setLetterCode(letterCode);
    }
    
    public void CureLetterRipObjectDataOnDemand.setReferenceNo(CureLetterRipObject obj, int index) {
        String referenceNo = "referenceNo_" + index;
        obj.setReferenceNo(referenceNo);
    }
    
    public void CureLetterRipObjectDataOnDemand.setRegistration1(CureLetterRipObject obj, int index) {
        String registration1 = "registration1_" + index;
        obj.setRegistration1(registration1);
    }
    
    public void CureLetterRipObjectDataOnDemand.setRegistration2(CureLetterRipObject obj, int index) {
        String registration2 = "registration2_" + index;
        obj.setRegistration2(registration2);
    }
    
    public void CureLetterRipObjectDataOnDemand.setRegistration3(CureLetterRipObject obj, int index) {
        String registration3 = "registration3_" + index;
        obj.setRegistration3(registration3);
    }
    
    public void CureLetterRipObjectDataOnDemand.setRegistration4(CureLetterRipObject obj, int index) {
        String registration4 = "registration4_" + index;
        obj.setRegistration4(registration4);
    }
    
    public void CureLetterRipObjectDataOnDemand.setRegistration5(CureLetterRipObject obj, int index) {
        String registration5 = "registration5_" + index;
        obj.setRegistration5(registration5);
    }
    
    public void CureLetterRipObjectDataOnDemand.setRegistration6(CureLetterRipObject obj, int index) {
        String registration6 = "registration6_" + index;
        obj.setRegistration6(registration6);
    }
    
    public void CureLetterRipObjectDataOnDemand.setSpecialInstructions(CureLetterRipObject obj, int index) {
        String specialInstructions = "specialInstructions_" + index;
        obj.setSpecialInstructions(specialInstructions);
    }
    
    public void CureLetterRipObjectDataOnDemand.setStateCode(CureLetterRipObject obj, int index) {
        String stateCode = "stateCode_" + index;
        obj.setStateCode(stateCode);
    }
    
    public void CureLetterRipObjectDataOnDemand.setWorkType(CureLetterRipObject obj, int index) {
        String workType = "workType_" + index;
        obj.setWorkType(workType);
    }
    
    public void CureLetterRipObjectDataOnDemand.setZipCode(CureLetterRipObject obj, int index) {
        String zipCode = "zipCode_" + index;
        obj.setZipCode(zipCode);
    }
    
    public void CureLetterRipObjectDataOnDemand.setZipExt(CureLetterRipObject obj, int index) {
        String zipExt = "zipExt_" + index;
        obj.setZipExt(zipExt);
    }
    
    public CureLetterRipObject CureLetterRipObjectDataOnDemand.getSpecificCureLetterRipObject(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CureLetterRipObject obj = data.get(index);
        Long id = obj.getId();
        return CureLetterRipObject.findCureLetterRipObject(id);
    }
    
    public CureLetterRipObject CureLetterRipObjectDataOnDemand.getRandomCureLetterRipObject() {
        init();
        CureLetterRipObject obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CureLetterRipObject.findCureLetterRipObject(id);
    }
    
    public boolean CureLetterRipObjectDataOnDemand.modifyCureLetterRipObject(CureLetterRipObject obj) {
        return false;
    }
    
    public void CureLetterRipObjectDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CureLetterRipObject.findCureLetterRipObjectEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CureLetterRipObject' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CureLetterRipObject>();
        for (int i = 0; i < 10; i++) {
            CureLetterRipObject obj = getNewTransientCureLetterRipObject(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
