// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.rip.domain;

import com.bfds.saec.rip.domain.SpecialhandlingRipObject;
import com.bfds.saec.rip.domain.SpecialhandlingRipObjectDataOnDemand;
import com.bfds.saec.rip.domain.SpecialhandlingRipObjectIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SpecialhandlingRipObjectIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SpecialhandlingRipObjectIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SpecialhandlingRipObjectIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SpecialhandlingRipObjectIntegrationTest: @Transactional;
    
    @Autowired
    private SpecialhandlingRipObjectDataOnDemand SpecialhandlingRipObjectIntegrationTest.dod;
    
    @Test
    public void SpecialhandlingRipObjectIntegrationTest.testCountSpecialhandlingRipObjects() {
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to initialize correctly", dod.getRandomSpecialhandlingRipObject());
        long count = SpecialhandlingRipObject.countSpecialhandlingRipObjects();
        Assert.assertTrue("Counter for 'SpecialhandlingRipObject' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SpecialhandlingRipObjectIntegrationTest.testFindSpecialhandlingRipObject() {
        SpecialhandlingRipObject obj = dod.getRandomSpecialhandlingRipObject();
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to provide an identifier", id);
        obj = SpecialhandlingRipObject.findSpecialhandlingRipObject(id);
        Assert.assertNotNull("Find method for 'SpecialhandlingRipObject' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SpecialhandlingRipObject' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SpecialhandlingRipObjectIntegrationTest.testFindAllSpecialhandlingRipObjects() {
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to initialize correctly", dod.getRandomSpecialhandlingRipObject());
        long count = SpecialhandlingRipObject.countSpecialhandlingRipObjects();
        Assert.assertTrue("Too expensive to perform a find all test for 'SpecialhandlingRipObject', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SpecialhandlingRipObject> result = SpecialhandlingRipObject.findAllSpecialhandlingRipObjects();
        Assert.assertNotNull("Find all method for 'SpecialhandlingRipObject' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SpecialhandlingRipObject' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SpecialhandlingRipObjectIntegrationTest.testFindSpecialhandlingRipObjectEntries() {
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to initialize correctly", dod.getRandomSpecialhandlingRipObject());
        long count = SpecialhandlingRipObject.countSpecialhandlingRipObjects();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SpecialhandlingRipObject> result = SpecialhandlingRipObject.findSpecialhandlingRipObjectEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SpecialhandlingRipObject' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SpecialhandlingRipObject' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SpecialhandlingRipObjectIntegrationTest.testFlush() {
        SpecialhandlingRipObject obj = dod.getRandomSpecialhandlingRipObject();
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to provide an identifier", id);
        obj = SpecialhandlingRipObject.findSpecialhandlingRipObject(id);
        Assert.assertNotNull("Find method for 'SpecialhandlingRipObject' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySpecialhandlingRipObject(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SpecialhandlingRipObject' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SpecialhandlingRipObjectIntegrationTest.testMergeUpdate() {
        SpecialhandlingRipObject obj = dod.getRandomSpecialhandlingRipObject();
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to provide an identifier", id);
        obj = SpecialhandlingRipObject.findSpecialhandlingRipObject(id);
        boolean modified =  dod.modifySpecialhandlingRipObject(obj);
        Integer currentVersion = obj.getVersion();
        SpecialhandlingRipObject merged = (SpecialhandlingRipObject)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SpecialhandlingRipObject' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SpecialhandlingRipObjectIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to initialize correctly", dod.getRandomSpecialhandlingRipObject());
        SpecialhandlingRipObject obj = dod.getNewTransientSpecialhandlingRipObject(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SpecialhandlingRipObject' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SpecialhandlingRipObject' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SpecialhandlingRipObjectIntegrationTest.testRemove() {
        SpecialhandlingRipObject obj = dod.getRandomSpecialhandlingRipObject();
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SpecialhandlingRipObject' failed to provide an identifier", id);
        obj = SpecialhandlingRipObject.findSpecialhandlingRipObject(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SpecialhandlingRipObject' with identifier '" + id + "'", SpecialhandlingRipObject.findSpecialhandlingRipObject(id));
    }
    
}
