// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.rip.domain;

import com.bfds.saec.rip.domain.SpecialhandlingRipObject;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SpecialhandlingRipObject_Roo_Configurable {
    
    declare @type: SpecialhandlingRipObject: @Configurable;
    
}
