/*
 * (c) Copyright 2005-2011 JAXIO - Generated by Celerio, a Jaxio tool. http://www.jaxio.com
 */
package com.bfds.saec.web.ui.el;

import java.io.Serializable;

import org.apache.commons.lang.StringUtils;
import org.springframework.stereotype.Component;

/**
 * Technical component to bypass EL limitation when passing
 * action parameter.
 * See iconAdd, iconEdit, etc. component tags.
 */
@Component
public class StringAction implements Serializable {
    private static final long serialVersionUID = 1L;

    private static final String DELETE = "delete";

    private static final String ADD = "add";

    private static final String EDIT = "edit";

    private static final String SELECT = "select";

    private static final String SEARCH = "search";

    private static final String VIEW = "view";

    public String add(final String action) {
        return this.custom(action, StringAction.ADD);
    }

    public String custom(final String action, final String defaut) {
        if (StringUtils.isEmpty(action)) {
            return defaut;
        }
        return action;
    }

    public String delete(final String action) {
        return this.custom(action, StringAction.DELETE);
    }

    public String edit(final String action) {
        return this.custom(action, StringAction.EDIT);
    }

    public String search(final String action) {
        return this.custom(action, StringAction.SEARCH);
    }

    public String select(final String action) {
        return this.custom(action, StringAction.SELECT);
    }

    public String view(final String action) {
        return this.custom(action, StringAction.VIEW);
    }
}
