// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain.activity;

import com.bfds.saec.domain.activity.CheckActivityDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CheckActivityDataOnDemand_Roo_Configurable {
    
    declare @type: CheckActivityDataOnDemand: @Configurable;
    
}
