// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain.activity;

import com.bfds.saec.domain.activity.PhoneCall;
import com.bfds.saec.domain.activity.PhoneCallDataOnDemand;
import com.bfds.saec.domain.activity.PhoneCallIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PhoneCallIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PhoneCallIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PhoneCallIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PhoneCallIntegrationTest: @Transactional;
    
    @Autowired
    private PhoneCallDataOnDemand PhoneCallIntegrationTest.dod;
    
    @Test
    public void PhoneCallIntegrationTest.testCountPhoneCalls() {
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to initialize correctly", dod.getRandomPhoneCall());
        long count = PhoneCall.countPhoneCalls();
        Assert.assertTrue("Counter for 'PhoneCall' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PhoneCallIntegrationTest.testFindPhoneCall() {
        PhoneCall obj = dod.getRandomPhoneCall();
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to provide an identifier", id);
        obj = PhoneCall.findPhoneCall(id);
        Assert.assertNotNull("Find method for 'PhoneCall' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PhoneCall' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PhoneCallIntegrationTest.testFindAllPhoneCalls() {
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to initialize correctly", dod.getRandomPhoneCall());
        long count = PhoneCall.countPhoneCalls();
        Assert.assertTrue("Too expensive to perform a find all test for 'PhoneCall', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PhoneCall> result = PhoneCall.findAllPhoneCalls();
        Assert.assertNotNull("Find all method for 'PhoneCall' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PhoneCall' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PhoneCallIntegrationTest.testFindPhoneCallEntries() {
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to initialize correctly", dod.getRandomPhoneCall());
        long count = PhoneCall.countPhoneCalls();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PhoneCall> result = PhoneCall.findPhoneCallEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PhoneCall' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PhoneCall' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PhoneCallIntegrationTest.testFlush() {
        PhoneCall obj = dod.getRandomPhoneCall();
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to provide an identifier", id);
        obj = PhoneCall.findPhoneCall(id);
        Assert.assertNotNull("Find method for 'PhoneCall' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPhoneCall(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PhoneCall' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhoneCallIntegrationTest.testMergeUpdate() {
        PhoneCall obj = dod.getRandomPhoneCall();
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to provide an identifier", id);
        obj = PhoneCall.findPhoneCall(id);
        boolean modified =  dod.modifyPhoneCall(obj);
        Integer currentVersion = obj.getVersion();
        PhoneCall merged = (PhoneCall)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PhoneCall' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhoneCallIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to initialize correctly", dod.getRandomPhoneCall());
        PhoneCall obj = dod.getNewTransientPhoneCall(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PhoneCall' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PhoneCall' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'PhoneCall' identifier to no longer be null", obj.getId());
    }
    
}
