// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain;

import com.bfds.saec.domain.HoldCode;
import javax.persistence.Entity;

privileged aspect HoldCode_Roo_Jpa_Entity {
    
    declare @type: HoldCode: @Entity;
    
}
