// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain.reference;

import com.bfds.saec.domain.reference.BankLov;
import javax.persistence.Entity;

privileged aspect BankLov_Roo_Jpa_Entity {
    
    declare @type: BankLov: @Entity;
    
}
