// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain.reference;

import com.bfds.saec.domain.reference.CountryLov;
import javax.persistence.Entity;

privileged aspect CountryLov_Roo_Jpa_Entity {
    
    declare @type: CountryLov: @Entity;
    
    public CountryLov.new() {
        super();
    }

}
