/*
 * (c) Copyright 2005-2011 JAXIO - Generated by Celerio, a Jaxio tool. http://www.jaxio.com
 */
package com.bfds.saec.web.service;

import java.util.List;

import com.bfds.saec.domain.Claimant;
import com.bfds.saec.domain.ClaimantAddress;
import com.bfds.saec.domain.audit.EntityWithAuditVo;
import com.bfds.saec.domain.dto.ClaimantSearchCriteriaDto;
import com.bfds.saec.domain.dto.ClaimantSearchRecordDto;

/**
 * The ClaimantService is a data-centric service for the Claimant entity.
 * It provides the expected methods to get/delete a Claimant instance
 * plus some methods to perform searches.
 *
 * Search logic is driven by 2 kinds of parameters: a Claimant instance used
 * as a properties holder against which the search will be performed and a SearchTemplate
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface ClaimantService {
	List<ClaimantSearchRecordDto> getClaimantSearchResults(ClaimantSearchCriteriaDto param);
	List<EntityWithAuditVo<ClaimantAddress>> getAddressVersionList(Long addressId);
	Long getClaimantSearchResultsCount(ClaimantSearchCriteriaDto param);
}