// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.wss.domain;

import com.bfds.wss.domain.ClaimFileLob;

privileged aspect ClaimFileLob_Roo_JavaBean {
    
    public byte[] ClaimFileLob.getData() {
        return this.data;
    }
    
    public void ClaimFileLob.setData(byte[] data) {
        this.data = data;
    }
    
}
