// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.wss.domain;

import com.bfds.wss.domain.ClaimUserResponseGroup;
import javax.persistence.Entity;

privileged aspect ClaimUserResponseGroup_Roo_Jpa_Entity {
    
    declare @type: ClaimUserResponseGroup: @Entity;
    
}
