// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain;

import com.bfds.saec.domain.CorrespondenceDocument;
import com.bfds.saec.domain.CorrespondenceDocumentDataOnDemand;
import com.bfds.saec.domain.CorrespondenceDocumentIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CorrespondenceDocumentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CorrespondenceDocumentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CorrespondenceDocumentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CorrespondenceDocumentIntegrationTest: @Transactional;
    
    @Autowired
    private CorrespondenceDocumentDataOnDemand CorrespondenceDocumentIntegrationTest.dod;
    
    @Test
    public void CorrespondenceDocumentIntegrationTest.testCountCorrespondenceDocuments() {
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to initialize correctly", dod.getRandomCorrespondenceDocument());
        long count = CorrespondenceDocument.countCorrespondenceDocuments();
        Assert.assertTrue("Counter for 'CorrespondenceDocument' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CorrespondenceDocumentIntegrationTest.testFindCorrespondenceDocument() {
        CorrespondenceDocument obj = dod.getRandomCorrespondenceDocument();
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to provide an identifier", id);
        obj = CorrespondenceDocument.findCorrespondenceDocument(id);
        Assert.assertNotNull("Find method for 'CorrespondenceDocument' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CorrespondenceDocument' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CorrespondenceDocumentIntegrationTest.testFindAllCorrespondenceDocuments() {
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to initialize correctly", dod.getRandomCorrespondenceDocument());
        long count = CorrespondenceDocument.countCorrespondenceDocuments();
        Assert.assertTrue("Too expensive to perform a find all test for 'CorrespondenceDocument', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CorrespondenceDocument> result = CorrespondenceDocument.findAllCorrespondenceDocuments();
        Assert.assertNotNull("Find all method for 'CorrespondenceDocument' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CorrespondenceDocument' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CorrespondenceDocumentIntegrationTest.testFindCorrespondenceDocumentEntries() {
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to initialize correctly", dod.getRandomCorrespondenceDocument());
        long count = CorrespondenceDocument.countCorrespondenceDocuments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CorrespondenceDocument> result = CorrespondenceDocument.findCorrespondenceDocumentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CorrespondenceDocument' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CorrespondenceDocument' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CorrespondenceDocumentIntegrationTest.testFlush() {
        CorrespondenceDocument obj = dod.getRandomCorrespondenceDocument();
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to provide an identifier", id);
        obj = CorrespondenceDocument.findCorrespondenceDocument(id);
        Assert.assertNotNull("Find method for 'CorrespondenceDocument' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCorrespondenceDocument(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CorrespondenceDocument' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CorrespondenceDocumentIntegrationTest.testMergeUpdate() {
        CorrespondenceDocument obj = dod.getRandomCorrespondenceDocument();
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to provide an identifier", id);
        obj = CorrespondenceDocument.findCorrespondenceDocument(id);
        boolean modified =  dod.modifyCorrespondenceDocument(obj);
        Integer currentVersion = obj.getVersion();
        CorrespondenceDocument merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CorrespondenceDocument' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CorrespondenceDocumentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to initialize correctly", dod.getRandomCorrespondenceDocument());
        CorrespondenceDocument obj = dod.getNewTransientCorrespondenceDocument(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CorrespondenceDocument' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CorrespondenceDocument' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'CorrespondenceDocument' identifier to no longer be null", obj.getId());
    }
    
}
