// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain;

import com.bfds.saec.domain.EventDataOnDemand;
import com.bfds.saec.domain.EventPaymentConfig;
import com.bfds.saec.domain.EventPaymentConfigDataOnDemand;
import com.bfds.saec.domain.PaymentComponentTypeLov;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EventPaymentConfigDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EventPaymentConfigDataOnDemand: @Component;
    
    private Random EventPaymentConfigDataOnDemand.rnd = new SecureRandom();
    
    private List<EventPaymentConfig> EventPaymentConfigDataOnDemand.data;
    
    @Autowired
    private EventDataOnDemand EventPaymentConfigDataOnDemand.eventDataOnDemand;
    
    public EventPaymentConfig EventPaymentConfigDataOnDemand.getNewTransientEventPaymentConfig(int index) {
        EventPaymentConfig obj = new EventPaymentConfig();
        setActive(obj, index);
        setActiveDescription(obj, index);
        setDefaultDescription(obj, index);
        setObjectCode(obj, index);
        setPaymentComponentType(obj, index);
        return obj;
    }
    
    public void EventPaymentConfigDataOnDemand.setActive(EventPaymentConfig obj, int index) {
        Boolean active = true;
        obj.setActive(active);
    }
    
    public void EventPaymentConfigDataOnDemand.setActiveDescription(EventPaymentConfig obj, int index) {
        String activeDescription = "activeDescription_" + index;
        obj.setActiveDescription(activeDescription);
    }
    
    public void EventPaymentConfigDataOnDemand.setDefaultDescription(EventPaymentConfig obj, int index) {
        String defaultDescription = "defaultDescription_" + index;
        obj.setDefaultDescription(defaultDescription);
    }
    
    public void EventPaymentConfigDataOnDemand.setObjectCode(EventPaymentConfig obj, int index) {
        char objectCode = 'N';
        obj.setObjectCode(objectCode);
    }
    
    public void EventPaymentConfigDataOnDemand.setPaymentComponentType(EventPaymentConfig obj, int index) {
        PaymentComponentTypeLov paymentComponentType = null;
        obj.setPaymentComponentType(paymentComponentType);
    }
    
    public EventPaymentConfig EventPaymentConfigDataOnDemand.getSpecificEventPaymentConfig(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EventPaymentConfig obj = data.get(index);
        Long id = obj.getId();
        return EventPaymentConfig.findEventPaymentConfig(id);
    }
    
    public EventPaymentConfig EventPaymentConfigDataOnDemand.getRandomEventPaymentConfig() {
        init();
        EventPaymentConfig obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return EventPaymentConfig.findEventPaymentConfig(id);
    }
    
    public boolean EventPaymentConfigDataOnDemand.modifyEventPaymentConfig(EventPaymentConfig obj) {
        return false;
    }
    
    public void EventPaymentConfigDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EventPaymentConfig.findEventPaymentConfigEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EventPaymentConfig' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EventPaymentConfig>();
        for (int i = 0; i < 10; i++) {
            EventPaymentConfig obj = getNewTransientEventPaymentConfig(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
