// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.domain;

import com.bfds.saec.domain.RequestType;
import com.bfds.saec.domain.RequestTypeDataOnDemand;
import com.bfds.saec.domain.RequestTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RequestTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RequestTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RequestTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RequestTypeIntegrationTest: @Transactional;
    
    @Autowired
    private RequestTypeDataOnDemand RequestTypeIntegrationTest.dod;
    
    @Test
    public void RequestTypeIntegrationTest.testCountRequestTypes() {
        Assert.assertNotNull("Data on demand for 'RequestType' failed to initialize correctly", dod.getRandomRequestType());
        long count = RequestType.countRequestTypes();
        Assert.assertTrue("Counter for 'RequestType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RequestTypeIntegrationTest.testFindRequestType() {
        RequestType obj = dod.getRandomRequestType();
        Assert.assertNotNull("Data on demand for 'RequestType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequestType' failed to provide an identifier", id);
        obj = RequestType.findRequestType(id);
        Assert.assertNotNull("Find method for 'RequestType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RequestType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RequestTypeIntegrationTest.testFindAllRequestTypes() {
        Assert.assertNotNull("Data on demand for 'RequestType' failed to initialize correctly", dod.getRandomRequestType());
        long count = RequestType.countRequestTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'RequestType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RequestType> result = RequestType.findAllRequestTypes();
        Assert.assertNotNull("Find all method for 'RequestType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RequestType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RequestTypeIntegrationTest.testFindRequestTypeEntries() {
        Assert.assertNotNull("Data on demand for 'RequestType' failed to initialize correctly", dod.getRandomRequestType());
        long count = RequestType.countRequestTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RequestType> result = RequestType.findRequestTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RequestType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RequestType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RequestTypeIntegrationTest.testFlush() {
        RequestType obj = dod.getRandomRequestType();
        Assert.assertNotNull("Data on demand for 'RequestType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequestType' failed to provide an identifier", id);
        obj = RequestType.findRequestType(id);
        Assert.assertNotNull("Find method for 'RequestType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRequestType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RequestType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RequestTypeIntegrationTest.testMergeUpdate() {
        RequestType obj = dod.getRandomRequestType();
        Assert.assertNotNull("Data on demand for 'RequestType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequestType' failed to provide an identifier", id);
        obj = RequestType.findRequestType(id);
        boolean modified =  dod.modifyRequestType(obj);
        Integer currentVersion = obj.getVersion();
        RequestType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RequestType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RequestTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RequestType' failed to initialize correctly", dod.getRandomRequestType());
        RequestType obj = dod.getNewTransientRequestType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RequestType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RequestType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RequestType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RequestTypeIntegrationTest.testRemove() {
        RequestType obj = dod.getRandomRequestType();
        Assert.assertNotNull("Data on demand for 'RequestType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RequestType' failed to provide an identifier", id);
        obj = RequestType.findRequestType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RequestType' with identifier '" + id + "'", RequestType.findRequestType(id));
    }
    
}
