// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bfds.saec.encorr.dao;

import com.bfds.saec.encorr.dao.EncorrItem;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect EncorrItem_Roo_Jpa_Entity {
    
    declare @type: EncorrItem: @Entity;
    
    declare @type: EncorrItem: @Table(name = "batch_encorr_item");
    
}
